mod 'puppet-nginx', '3.0.0'
mod 'puppetlabs-concat', '6.4.0'
mod 'puppetlabs-translate', '2.2.0'
mod 'puppetlabs-stdlib', '6.6.0'
mod 'puppetlabs-docker', '3.13.1'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-apt', '7.7.1'
